### ISSUE TITLE
def test_forward_prop_routine

### ISSUE THREAD

**Issue by atakanserin** [JulianoLagana/deep-machine-learning#11]
Hi,
In ha2Tests.py for testing forward propagation, function test_forward_prop_routine is utilized. However inside this function, 'assert' statements are only written for dimension checking of ys_pred[]. Actually it is told in the printout at the end: 'print('test passed, dimensions are correct')'. So I think it is actually known or might be done intentionally. However I think it needs more 'assert' statements for checking ys_pred[] results since test passes with wrong ys_pred[], hs[] dimensions results and hs[] results. So it can be misleading for those cases.
Thanks
Mehmet Atakan Serin

**Comment by JulianoLagana** [comment]
Thanks @atakanserin. I think we both agree that this is not actually a bug, but this test can indeed be improved.
