### ISSUE TITLE
CSV file for IHA2 missing?

### ISSUE THREAD

**Issue by luckyluks** [JulianoLagana/deep-machine-learning#14]
Will the '300k.csv' file of the Predict'em All dataset from Kaggle for IHA2 be included in the repo or do we have to create an Kaggle account and integrate it for ourselves?

Greets
Lukas

**Comment by lucasbrynte** [comment]
I don't think we are allowed by Kaggle to distribute the file, so you need to get the file from Kaggle yourselves. I'm not sure you need to create account but that might be the case.
