### ISSUE TITLE
Missing link to Google Forms when following Google Cloud instructions

### ISSUE THREAD

**Issue by Nosskirneh** [JulianoLagana/deep-machine-learning#19]
Per the instructions for setting up a Google Cloud account, we should fill in a form to let you know which Gmail address that will be used in this course. However, there is [no link in the instructions](https://github.com/JulianoLagana/deep-machine-learning/blame/master/instructions/02b_google_cloud_instructions.md#L15).

Just figured I'd let you know in case this was forgotten. Thanks!

**Comment by JulianoLagana** [comment]
Thanks for letting us know! Fixed with commits 165a2a0eba39facdba0a7a9673a8611de7d2fdf6 and ce0647a228fda967c3cd915fbde76752c9005028. @lucasbrynte, please review.
