### ISSUE TITLE
relu, and test_relu. Wrong description?

### ISSUE THREAD

**Issue by almenjonatan** [JulianoLagana/deep-machine-learning#2]
In the ReLU function it says that input is ```numpy.ndarray```, If I'm not mistaken taking a look at ```test_relu``` it feeds ```relu``` function with numpy.float64. It then tests the output should be the same size as the input, should we consider scalar values aswell as ndarray input or have I missed something?

**Comment by JulianoLagana** [comment]
Hej @skyw00lker. I believe this was solved with commit 5ee89d2612b53ae75eb7538754a6ec7c35662c23. Isn't that the case?

**Comment by skyw00lker** [comment]
No, it's still get floats numpy.float64, and ndarray. It's easy to workaround but I think it should be changed.

**Comment by JulianoLagana** [comment]
Upon closer look to `iha1tests.py` I now agree with you.  Thanks for pointing it out.
