### ISSUE TITLE
Error in test_backward_prop : Precision issue

### ISSUE THREAD

**Issue by dimkary** [JulianoLagana/deep-machine-learning#6]
In the `backward_prop_routine`, in the part where we compute the delta_L / delta_h_t you might encounter a precision issue. The matrix multiplication of d[t+1] * W_hh.T, if the calculation is conducted using the numpy method `np.dot()`, you might receive slightly different gradients than expected. In particular, I received the following exit message:

`The gradient computed for dL/dW_xh(0,0) is incorrect. No further terms in W_xh will be tested before you fix this error.
Provided: -5.20047973326743e-05 	Expected: -5.005906800192861e-05 	(3.8868668722932127% off)`

`The gradient computed for dL/db_h(0,0) is incorrect.
No further terms in b_h will be tested before you fix this error.
Provided: -9.028898827635241e-05`

However, if you conduct the multiplication with the `@` operator, it works smoothly. The probable issue is that the `@` symbol invokes the `np.matmul()` method. They calculate the inner product in a bit different way. Some info can be found at [https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication](url). 
For backpropagation, I used the `np.dot()` and just for the dL/dh[t] part I used the `@` operator and it works. A higher difference threshold for the tester file might be a good idea. If not it should be commented in the default HA2.ipynb

Hope this helps ;-)

**Comment by dimkary** [comment]
I actually tried to use `np.matmul()` explicitly, but still got the same error. It seems that only the `@` matrix multiplication method works for the problematic part, so better stick to it.

**Comment by lucasbrynte** [comment]
https://pingpong.chalmers.se/courseId/9763/courseDiscussListPosts.do?id=139635

**Comment by JulianoLagana** [comment]
Hey @dimkary. I'm guessing this was a problem related to how each term is grouped if you're using parenthesis or relying on the operator precedence of `@`. Can you please take a look at #7 and see if this was the case for you? If so, we can close this issue.

**Comment by JulianoLagana** [comment]
Even better: I'll close this issue now. If what I said above does not apply to you, please reopen the issue with further explanations ;).
