### ISSUE TITLE
order of list(set([x, y, z])) undefined

### ISSUE THREAD

**Issue by erikstenborg** [JulianoLagana/deep-machine-learning#9]
In HA2 there is some code which generates a word list from the input sentences. However, this method seems to not be deterministic and gives a different ordering when you run it multiple times (with kernel restarts inbetween). This becomes a problem when using a saved model, which was trained with a differently ordered word list, since the translate function will not work unless the ordering is the same. I recommend you to sort the list, so that the order becomes deterministic:

eng_vocab = list(set([word for sentence in eng for word in sentence.split(' ')]))
eng_vocab.sort()
eng_ix_to_word = ['ZERO'] + eng_vocab + ['UNK']
eng_word_to_ix =  { word: index for index, word in enumerate(eng_ix_to_word)}
spa_vocab = list(set([word for sentence in spa for word in sentence.split(' ')]))
spa_vocab.sort()
spa_ix_to_word = ['ZERO'] + spa_vocab + ['UNK']
spa_word_to_ix =  { word: index for index, word in enumerate(spa_ix_to_word)}

**Comment by fsharpasharp** [comment]
This is easily reproducible by starting Python and taking the set of a list of words, restarting Python and taking the set of the same list of words. There is no deterministic order for the same list of words and the ordering is probably hash based. @erikstenborg should make a pull request to fix this.

**Comment by JulianoLagana** [comment]
Solved with commit 327ef49427c2c53da289f0a93f28d7e8ac40ce07.
